---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logs
  labels:
    app: kibana-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-logs
  template:
    metadata:
      labels:
        app: kibana-logs
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:6.6.0
        name: kibana-logs
        env:
        - name: ELASTICSEARCH_URL
          value: {{ .Values.elasticsearchUrl }}
        - name: xpack.monitoring.ui.container.elasticsearch.enabled
          value: "false"
        - name: NODE_OPTIONS
          value: "--max_old_space_size={{ .Values.oldSpaceSizeInMb }}"
        ports:
        - name: web
          containerPort: 5601
