kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-configmap
data:
  fluent.conf: |-
    <match fluent.**>
      @type null
    </match>

    <source>
      @id java
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/java-containers.log.pos
      tag java.*
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    <match **fluentd**.log>
      @type null
    </match>

    # Enriches records with Kubernetes metadata
    <filter **>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>

    # Fixes json fields in Elasticsearch
    <filter **>
      @id filter_parser
      @type parser
      key_name log
      reserve_data true
      reserve_time true
      remove_key_name_field true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>

    # Concatenate multi-line logs
    <filter java.**>
      @id filter_concat_java
      @type concat
      reserve_data true
      reserve_time true
      use_first_timestamp true
      key message
      multiline_start_regexp /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/
      separator ""
      flush_interval 2
      timeout_label @NORMAL
    </filter>

    <match **>
      @type relabel
      @label @NORMAL
    </match>

    <label @NORMAL>
      <match **>
        @id elasticsearch
        @type elasticsearch
        @log_level info
        type_name _doc
        include_tag_key true
        host elasticsearch-logs
        port 9200
        logstash_format true
        reload_connections false
        reconnect_on_error true
        reload_on_failure true
        <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.system.buffer
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 4
          flush_interval 5s
          retry_forever true
          retry_max_interval 30
          chunk_limit_size 2M
          queue_limit_length 32
          overflow_action block
        </buffer>
      </match>
    </label>